#修改默认端口号
server:
  port: 8888

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java352
    username: root
    password: root

  #配置thymeleaf
  thymeleaf:
    enabled: true
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    model: HTML5
    check-template-location: true
    content-type: text/html

#配置mapper扫描的文件
mybatis:
    mapper-locations: classpath:/mapper/*.xml
